### ISSUE TITLE
Investigate using the new Kotlin analysis API

### ISSUE THREAD

**Issue by gAbelli** [Kotlin-Language-Server/kotlin-language-server#25]
The original repository has an open issue that mentions the possibility to use the analysis API to implement a language server for Kotlin: https://github.com/fwcd/kotlin-language-server/issues/289.
I was wondering if this has been further investigated, or if there are plans to do so in the future.
Thanks for the great work by the way, it would be amazing to have a fully functional LSP for Kotlin!

**Comment by amgdev9** [comment]
A couple of months ago I did investigate the api to do incremental analysis, not working atm but I think this approach goes in the right direction. I share it in case someone wants to continue the research: https://github.com/fwcd/kotlin-analysis-server/issues/1#issuecomment-2518453803

**Comment by gAbelli** [comment]
[This thread](https://kotlinlang.slack.com/archives/C7L3JB43G/p1731746944487129) in the Kotlin compiler Slack channel might be relevant.
```
The standalone part is still in the development state
https://kotlin.github.io/analysis-api/index_md.html#using-in-command-line-tools
It has been designed as an immutable view on the code, so it is not supposed to react on changes (at least yet)
```
```
The Standalone mode indeed doesn't support file mutation now.
Still, would you be able to provide your use-case? We are going to activate the Standalone platform development, so now we are interested in popular use-cases.
```
So it looks like the best we can do is letting JetBrains know that file mutation would be a useful feature for this use-case, and wait.

**Comment by amgdev9** [comment]
@gAbelli After months of research I finally got file mutation to work using analysis api, not using standalone but implementing my own custom platform, as an AA developer suggested me. PoC here: https://github.com/amgdev9/kotlin-lsp

**Comment by gAbelli** [comment]
> [@gAbelli](https://github.com/gAbelli) After months of research I finally got file mutation to work using analysis api, not using standalone but implementing my own custom platform, as an AA developer suggested me. PoC here: https://github.com/amgdev9/kotlin-lsp

That's impressive, I'll definitely take a look! What are you planning to do next? Do you see any big obstacles for turning it into a working language server?

**Comment by amgdev9** [comment]
> > [@gAbelli](https://github.com/gAbelli) After months of research I finally got file mutation to work using analysis api, not using standalone but implementing my own custom platform, as an AA developer suggested me. PoC here: https://github.com/amgdev9/kotlin-lsp
> 
> That's impressive, I'll definitely take a look! What are you planning to do next? Do you see any big obstacles for turning it into a working language server?

I dont see any major blockers, just a ton of developer time I currently dont have 😅. The biggest parts to do are the indexing (which is already done in the current kotlin lsp, but the caching mechanism can definitely be improved) and build system integration which needs some adjustments, but again it is just an issue of having manpower to do it

In my case I try to improve it when i have some spare time, the goal right now is to finish implementing the remaining services so imports are resolved correctly (right now they arr working for source files but not for library dependencies). Im open to contributions and answering questions about this implementation!

**Comment by gAbelli** [comment]
@amgdev9 I'm currently working on another project but I would like to check out what you did once I'm done! What do you think about adding a README that gives a brief explanation of how your implementation works and what is still missing? It might make it easier for people like me to contribute to the project.

**Comment by amgdev9** [comment]
> [@amgdev9](https://github.com/amgdev9) I'm currently working on another project but I would like to check out what you did once I'm done! What do you think about adding a README that gives a brief explanation of how your implementation works and what is still missing? It might make it easier for people like me to contribute to the project.

Done! I added a readme explaining how to build and run the project, its current status and the missing pieces to implement 😄
